### ISSUE TITLE
Feature request: Ability to order tables

### ISSUE THREAD

**Issue by admench** [beyondcode/laravel-masked-db-dump#10]
It would be great to be able to set certain tables to be at the start of the sql file, so that when importing, foreign key checks don't fail. 

Many thanks for an amazing package. If I can I will try to submit PR for this.

**Comment by admench** [comment]
A workaround for this issue is to do the following: 
At the start of the dump file, insert `SET FOREIGN_KEY_CHECKS=0;` and then at the end insert `SET FOREIGN_KEY_CHECKS=1;` which bypasses the checks and means the Dump works without errors. 

...perhaps this could be a flag to add to the command to automatically add these lines as an option. 🤔

**Comment by sidigi** [comment]
Nope, we need this feature) Please open)
