### ISSUE TITLE
Can't restore dumps on PostgreSQL

### ISSUE THREAD

**Issue by gjm** [beyondcode/laravel-masked-db-dump#12]
Trying to restore a dump created with the package on a PostgreSQL server doesn't work and produces a lot of errors. 

Here's a snippet:
```sql
CREATE TABLE
ERROR:  syntax error at or near "`"
LINE 1: LOCK TABLES `sandbox_documents` WRITE;
                    ^
ERROR:  syntax error at or near "`"
LINE 1: ALTER TABLE `sandbox_documents` DISABLE KEYS;
                    ^
ERROR:  syntax error at or near "`"
LINE 1: ALTER TABLE `sandbox_documents` ENABLE KEYS;
```

The relevant SQL in the generated dump:

```sql
LOCK TABLES `sandbox_documents` WRITE;
ALTER TABLE `sandbox_documents` DISABLE KEYS;
ALTER TABLE `sandbox_documents` ENABLE KEYS;
```

PostgreSQL uses double quote for escaping keywords and not back quote.

**Comment by mechelon** [comment]
While it was not specified clearly anywhere - this package was meant to be used with MySQL. Postgres works with 3.0.0 as well (please take a look at the breaking changes).
