### ISSUE TITLE
Support for PHP8.0

### ISSUE THREAD

**Issue by SebastianSchoeps** [beyondcode/laravel-masked-db-dump#3]
Is it only accidentally that PHP 8.0 is not contained in composer.json, or does this really not work with PHP8?

**Comment by mokhosh** [comment]
```
  [InvalidArgumentException]                                                                                                               
  Package beyondcode/laravel-masked-db-dump has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version 
```

I'm running on macos with php 8.0.2

**Comment by mokhosh** [comment]
Fixed it like this until the PR gets merged
```
 composer require beyondcode/laravel-masked-db-dump --ignore-platform-reqs
```
I also needed to swap out `fzaninotto/faker` with Laravel with `fakerphp/faker`

**Comment by karenirenecano** [comment]
came here with the same issue +1

**Comment by peterjthomson** [comment]
Why was this comment closed? From my composer error (today):
    - beyondcode/laravel-masked-db-dump 1.0.0 requires php ^7.3 -> your php version (8.0.12) does not satisfy that requirement.
